/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CopyCorpusRequestModel from '../model/CopyCorpusRequestModel';
import CreateRevisionRequestModel from '../model/CreateRevisionRequestModel';
import ErrorModel from '../model/ErrorModel';
import HTTPValidationError from '../model/HTTPValidationError';
import ItemCountResponseModel from '../model/ItemCountResponseModel';
import ListRevisionsResponseModel from '../model/ListRevisionsResponseModel';
import ORMHealth from '../model/ORMHealth';
import ORMRevisionStatus from '../model/ORMRevisionStatus';
import RevisionResponseModel from '../model/RevisionResponseModel';
import SetActiveRevisionRequestModel from '../model/SetActiveRevisionRequestModel';
import UpdateRevisionInfoRequestModel from '../model/UpdateRevisionInfoRequestModel';
import UpdateRevisionResourcesRequestModel from '../model/UpdateRevisionResourcesRequestModel';

/**
* Revisions service.
* @module api/RevisionsApi
* @version 0.1.0
*/
export default class RevisionsApi {

    /**
    * Constructs a new RevisionsApi. 
    * @alias module:api/RevisionsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Copy Corpus Files
     * @param {String} dstRevId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @param {module:model/CopyCorpusRequestModel} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    copyCorpusFilesWithHttpInfo(dstRevId, userId, projectId, fuzzerId, body) {
      let postBody = body;
      // verify the required parameter 'dstRevId' is set
      if (dstRevId === undefined || dstRevId === null) {
        throw new Error("Missing the required parameter 'dstRevId' when calling copyCorpusFiles");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling copyCorpusFiles");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling copyCorpusFiles");
      }
      // verify the required parameter 'fuzzerId' is set
      if (fuzzerId === undefined || fuzzerId === null) {
        throw new Error("Missing the required parameter 'fuzzerId' when calling copyCorpusFiles");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling copyCorpusFiles");
      }

      let pathParams = {
        'dst_rev_id': dstRevId,
        'user_id': userId,
        'project_id': projectId,
        'fuzzer_id': fuzzerId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/users/{user_id}/projects/{project_id}/fuzzers/{fuzzer_id}/revisions/{dst_rev_id}/files/corpus', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Copy Corpus Files
     * @param {String} dstRevId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @param {module:model/CopyCorpusRequestModel} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    copyCorpusFiles(dstRevId, userId, projectId, fuzzerId, body) {
      return this.copyCorpusFilesWithHttpInfo(dstRevId, userId, projectId, fuzzerId, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create Revision
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @param {module:model/CreateRevisionRequestModel} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RevisionResponseModel} and HTTP response
     */
    createRevisionWithHttpInfo(userId, projectId, fuzzerId, body) {
      let postBody = body;
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling createRevision");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling createRevision");
      }
      // verify the required parameter 'fuzzerId' is set
      if (fuzzerId === undefined || fuzzerId === null) {
        throw new Error("Missing the required parameter 'fuzzerId' when calling createRevision");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createRevision");
      }

      let pathParams = {
        'user_id': userId,
        'project_id': projectId,
        'fuzzer_id': fuzzerId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = RevisionResponseModel;
      return this.apiClient.callApi(
        '/api/v1/users/{user_id}/projects/{project_id}/fuzzers/{fuzzer_id}/revisions', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create Revision
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @param {module:model/CreateRevisionRequestModel} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RevisionResponseModel}
     */
    createRevision(userId, projectId, fuzzerId, body) {
      return this.createRevisionWithHttpInfo(userId, projectId, fuzzerId, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete Revision
     * @param {String} revisionId 
     * @param {String} fuzzerId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {module:model/String} action An enumeration.
     * @param {Object} opts Optional parameters
     * @param {String} opts.newName 
     * @param {Boolean} opts.noBackup  (default to false)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    deleteRevisionWithHttpInfo(revisionId, fuzzerId, userId, projectId, action, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'revisionId' is set
      if (revisionId === undefined || revisionId === null) {
        throw new Error("Missing the required parameter 'revisionId' when calling deleteRevision");
      }
      // verify the required parameter 'fuzzerId' is set
      if (fuzzerId === undefined || fuzzerId === null) {
        throw new Error("Missing the required parameter 'fuzzerId' when calling deleteRevision");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling deleteRevision");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling deleteRevision");
      }
      // verify the required parameter 'action' is set
      if (action === undefined || action === null) {
        throw new Error("Missing the required parameter 'action' when calling deleteRevision");
      }

      let pathParams = {
        'revision_id': revisionId,
        'fuzzer_id': fuzzerId,
        'user_id': userId,
        'project_id': projectId
      };
      let queryParams = {
        'new_name': opts['newName'],
        'action': action,
        'no_backup': opts['noBackup']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/users/{user_id}/projects/{project_id}/fuzzers/{fuzzer_id}/revisions/{revision_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete Revision
     * @param {String} revisionId 
     * @param {String} fuzzerId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {module:model/String} action An enumeration.
     * @param {Object} opts Optional parameters
     * @param {String} opts.newName 
     * @param {Boolean} opts.noBackup  (default to false)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    deleteRevision(revisionId, fuzzerId, userId, projectId, action, opts) {
      return this.deleteRevisionWithHttpInfo(revisionId, fuzzerId, userId, projectId, action, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Download Revision Binaries
     * @param {String} revisionId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    downloadRevisionBinariesWithHttpInfo(revisionId, userId, projectId, fuzzerId) {
      let postBody = null;
      // verify the required parameter 'revisionId' is set
      if (revisionId === undefined || revisionId === null) {
        throw new Error("Missing the required parameter 'revisionId' when calling downloadRevisionBinaries");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling downloadRevisionBinaries");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling downloadRevisionBinaries");
      }
      // verify the required parameter 'fuzzerId' is set
      if (fuzzerId === undefined || fuzzerId === null) {
        throw new Error("Missing the required parameter 'fuzzerId' when calling downloadRevisionBinaries");
      }

      let pathParams = {
        'revision_id': revisionId,
        'user_id': userId,
        'project_id': projectId,
        'fuzzer_id': fuzzerId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/octet-stream'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/users/{user_id}/projects/{project_id}/fuzzers/{fuzzer_id}/revisions/{revision_id}/files/binaries', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Download Revision Binaries
     * @param {String} revisionId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    downloadRevisionBinaries(revisionId, userId, projectId, fuzzerId) {
      return this.downloadRevisionBinariesWithHttpInfo(revisionId, userId, projectId, fuzzerId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Download Revision Config
     * @param {String} revisionId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    downloadRevisionConfigWithHttpInfo(revisionId, userId, projectId, fuzzerId) {
      let postBody = null;
      // verify the required parameter 'revisionId' is set
      if (revisionId === undefined || revisionId === null) {
        throw new Error("Missing the required parameter 'revisionId' when calling downloadRevisionConfig");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling downloadRevisionConfig");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling downloadRevisionConfig");
      }
      // verify the required parameter 'fuzzerId' is set
      if (fuzzerId === undefined || fuzzerId === null) {
        throw new Error("Missing the required parameter 'fuzzerId' when calling downloadRevisionConfig");
      }

      let pathParams = {
        'revision_id': revisionId,
        'user_id': userId,
        'project_id': projectId,
        'fuzzer_id': fuzzerId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/octet-stream'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/users/{user_id}/projects/{project_id}/fuzzers/{fuzzer_id}/revisions/{revision_id}/files/config', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Download Revision Config
     * @param {String} revisionId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    downloadRevisionConfig(revisionId, userId, projectId, fuzzerId) {
      return this.downloadRevisionConfigWithHttpInfo(revisionId, userId, projectId, fuzzerId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Download Revision Seeds
     * @param {String} revisionId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    downloadRevisionSeedsWithHttpInfo(revisionId, userId, projectId, fuzzerId) {
      let postBody = null;
      // verify the required parameter 'revisionId' is set
      if (revisionId === undefined || revisionId === null) {
        throw new Error("Missing the required parameter 'revisionId' when calling downloadRevisionSeeds");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling downloadRevisionSeeds");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling downloadRevisionSeeds");
      }
      // verify the required parameter 'fuzzerId' is set
      if (fuzzerId === undefined || fuzzerId === null) {
        throw new Error("Missing the required parameter 'fuzzerId' when calling downloadRevisionSeeds");
      }

      let pathParams = {
        'revision_id': revisionId,
        'user_id': userId,
        'project_id': projectId,
        'fuzzer_id': fuzzerId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/octet-stream'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/users/{user_id}/projects/{project_id}/fuzzers/{fuzzer_id}/revisions/{revision_id}/files/seeds', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Download Revision Seeds
     * @param {String} revisionId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    downloadRevisionSeeds(revisionId, userId, projectId, fuzzerId) {
      return this.downloadRevisionSeedsWithHttpInfo(revisionId, userId, projectId, fuzzerId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Active Revision
     * Get active revision
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RevisionResponseModel} and HTTP response
     */
    getActiveRevisionWithHttpInfo(userId, projectId, fuzzerId) {
      let postBody = null;
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling getActiveRevision");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling getActiveRevision");
      }
      // verify the required parameter 'fuzzerId' is set
      if (fuzzerId === undefined || fuzzerId === null) {
        throw new Error("Missing the required parameter 'fuzzerId' when calling getActiveRevision");
      }

      let pathParams = {
        'user_id': userId,
        'project_id': projectId,
        'fuzzer_id': fuzzerId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = RevisionResponseModel;
      return this.apiClient.callApi(
        '/api/v1/users/{user_id}/projects/{project_id}/fuzzers/{fuzzer_id}/revisions/active', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Active Revision
     * Get active revision
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RevisionResponseModel}
     */
    getActiveRevision(userId, projectId, fuzzerId) {
      return this.getActiveRevisionWithHttpInfo(userId, projectId, fuzzerId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Revision
     * @param {String} revisionId 
     * @param {String} fuzzerId 
     * @param {String} userId 
     * @param {String} projectId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RevisionResponseModel} and HTTP response
     */
    getRevisionWithHttpInfo(revisionId, fuzzerId, userId, projectId) {
      let postBody = null;
      // verify the required parameter 'revisionId' is set
      if (revisionId === undefined || revisionId === null) {
        throw new Error("Missing the required parameter 'revisionId' when calling getRevision");
      }
      // verify the required parameter 'fuzzerId' is set
      if (fuzzerId === undefined || fuzzerId === null) {
        throw new Error("Missing the required parameter 'fuzzerId' when calling getRevision");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling getRevision");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling getRevision");
      }

      let pathParams = {
        'revision_id': revisionId,
        'fuzzer_id': fuzzerId,
        'user_id': userId,
        'project_id': projectId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = RevisionResponseModel;
      return this.apiClient.callApi(
        '/api/v1/users/{user_id}/projects/{project_id}/fuzzers/{fuzzer_id}/revisions/{revision_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Revision
     * @param {String} revisionId 
     * @param {String} fuzzerId 
     * @param {String} userId 
     * @param {String} projectId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RevisionResponseModel}
     */
    getRevision(revisionId, fuzzerId, userId, projectId) {
      return this.getRevisionWithHttpInfo(revisionId, fuzzerId, userId, projectId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Revision By Name
     * @param {String} fuzzerId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} name 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RevisionResponseModel} and HTTP response
     */
    getRevisionByNameWithHttpInfo(fuzzerId, userId, projectId, name) {
      let postBody = null;
      // verify the required parameter 'fuzzerId' is set
      if (fuzzerId === undefined || fuzzerId === null) {
        throw new Error("Missing the required parameter 'fuzzerId' when calling getRevisionByName");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling getRevisionByName");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling getRevisionByName");
      }
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling getRevisionByName");
      }

      let pathParams = {
        'fuzzer_id': fuzzerId,
        'user_id': userId,
        'project_id': projectId
      };
      let queryParams = {
        'name': name
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = RevisionResponseModel;
      return this.apiClient.callApi(
        '/api/v1/users/{user_id}/projects/{project_id}/fuzzers/{fuzzer_id}/revisions/lookup', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Revision By Name
     * @param {String} fuzzerId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} name 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RevisionResponseModel}
     */
    getRevisionByName(fuzzerId, userId, projectId, name) {
      return this.getRevisionByNameWithHttpInfo(fuzzerId, userId, projectId, name)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Revision Count
     * @param {String} fuzzerId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {Object} opts Optional parameters
     * @param {Number} opts.pgSize  (default to 100)
     * @param {module:model/String} opts.removalState An enumeration.
     * @param {Array.<module:model/ORMRevisionStatus>} opts.statuses 
     * @param {Array.<module:model/ORMHealth>} opts.health 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ItemCountResponseModel} and HTTP response
     */
    getRevisionCountWithHttpInfo(fuzzerId, userId, projectId, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'fuzzerId' is set
      if (fuzzerId === undefined || fuzzerId === null) {
        throw new Error("Missing the required parameter 'fuzzerId' when calling getRevisionCount");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling getRevisionCount");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling getRevisionCount");
      }

      let pathParams = {
        'fuzzer_id': fuzzerId,
        'user_id': userId,
        'project_id': projectId
      };
      let queryParams = {
        'pg_size': opts['pgSize'],
        'removal_state': opts['removalState'],
        'statuses': this.apiClient.buildCollectionParam(opts['statuses'], 'multi'),
        'health': this.apiClient.buildCollectionParam(opts['health'], 'multi')
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ItemCountResponseModel;
      return this.apiClient.callApi(
        '/api/v1/users/{user_id}/projects/{project_id}/fuzzers/{fuzzer_id}/revisions/count', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Revision Count
     * @param {String} fuzzerId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {Object} opts Optional parameters
     * @param {Number} opts.pgSize  (default to 100)
     * @param {module:model/String} opts.removalState An enumeration.
     * @param {Array.<module:model/ORMRevisionStatus>} opts.statuses 
     * @param {Array.<module:model/ORMHealth>} opts.health 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ItemCountResponseModel}
     */
    getRevisionCount(fuzzerId, userId, projectId, opts) {
      return this.getRevisionCountWithHttpInfo(fuzzerId, userId, projectId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * List Revisions
     * @param {String} fuzzerId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {Object} opts Optional parameters
     * @param {Number} opts.pgSize  (default to 100)
     * @param {Number} opts.pgNum  (default to 0)
     * @param {module:model/String} opts.removalState An enumeration.
     * @param {Array.<module:model/ORMRevisionStatus>} opts.statuses 
     * @param {Array.<module:model/ORMHealth>} opts.health 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ListRevisionsResponseModel} and HTTP response
     */
    listRevisionsWithHttpInfo(fuzzerId, userId, projectId, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'fuzzerId' is set
      if (fuzzerId === undefined || fuzzerId === null) {
        throw new Error("Missing the required parameter 'fuzzerId' when calling listRevisions");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling listRevisions");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling listRevisions");
      }

      let pathParams = {
        'fuzzer_id': fuzzerId,
        'user_id': userId,
        'project_id': projectId
      };
      let queryParams = {
        'pg_size': opts['pgSize'],
        'pg_num': opts['pgNum'],
        'removal_state': opts['removalState'],
        'statuses': this.apiClient.buildCollectionParam(opts['statuses'], 'multi'),
        'health': this.apiClient.buildCollectionParam(opts['health'], 'multi')
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListRevisionsResponseModel;
      return this.apiClient.callApi(
        '/api/v1/users/{user_id}/projects/{project_id}/fuzzers/{fuzzer_id}/revisions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List Revisions
     * @param {String} fuzzerId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {Object} opts Optional parameters
     * @param {Number} opts.pgSize  (default to 100)
     * @param {Number} opts.pgNum  (default to 0)
     * @param {module:model/String} opts.removalState An enumeration.
     * @param {Array.<module:model/ORMRevisionStatus>} opts.statuses 
     * @param {Array.<module:model/ORMHealth>} opts.health 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ListRevisionsResponseModel}
     */
    listRevisions(fuzzerId, userId, projectId, opts) {
      return this.listRevisionsWithHttpInfo(fuzzerId, userId, projectId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Restart Revision
     * @param {String} revisionId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    restartRevisionWithHttpInfo(revisionId, userId, projectId, fuzzerId) {
      let postBody = null;
      // verify the required parameter 'revisionId' is set
      if (revisionId === undefined || revisionId === null) {
        throw new Error("Missing the required parameter 'revisionId' when calling restartRevision");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling restartRevision");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling restartRevision");
      }
      // verify the required parameter 'fuzzerId' is set
      if (fuzzerId === undefined || fuzzerId === null) {
        throw new Error("Missing the required parameter 'fuzzerId' when calling restartRevision");
      }

      let pathParams = {
        'revision_id': revisionId,
        'user_id': userId,
        'project_id': projectId,
        'fuzzer_id': fuzzerId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/users/{user_id}/projects/{project_id}/fuzzers/{fuzzer_id}/revisions/{revision_id}/actions/restart', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Restart Revision
     * @param {String} revisionId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    restartRevision(revisionId, userId, projectId, fuzzerId) {
      return this.restartRevisionWithHttpInfo(revisionId, userId, projectId, fuzzerId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Set Active Revision
     * Set active revision
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @param {module:model/SetActiveRevisionRequestModel} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    setActiveRevisionWithHttpInfo(userId, projectId, fuzzerId, body) {
      let postBody = body;
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling setActiveRevision");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling setActiveRevision");
      }
      // verify the required parameter 'fuzzerId' is set
      if (fuzzerId === undefined || fuzzerId === null) {
        throw new Error("Missing the required parameter 'fuzzerId' when calling setActiveRevision");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling setActiveRevision");
      }

      let pathParams = {
        'user_id': userId,
        'project_id': projectId,
        'fuzzer_id': fuzzerId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/users/{user_id}/projects/{project_id}/fuzzers/{fuzzer_id}/revisions/active', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Set Active Revision
     * Set active revision
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @param {module:model/SetActiveRevisionRequestModel} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    setActiveRevision(userId, projectId, fuzzerId, body) {
      return this.setActiveRevisionWithHttpInfo(userId, projectId, fuzzerId, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Start Revision
     * @param {String} revisionId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    startRevisionWithHttpInfo(revisionId, userId, projectId, fuzzerId) {
      let postBody = null;
      // verify the required parameter 'revisionId' is set
      if (revisionId === undefined || revisionId === null) {
        throw new Error("Missing the required parameter 'revisionId' when calling startRevision");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling startRevision");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling startRevision");
      }
      // verify the required parameter 'fuzzerId' is set
      if (fuzzerId === undefined || fuzzerId === null) {
        throw new Error("Missing the required parameter 'fuzzerId' when calling startRevision");
      }

      let pathParams = {
        'revision_id': revisionId,
        'user_id': userId,
        'project_id': projectId,
        'fuzzer_id': fuzzerId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/users/{user_id}/projects/{project_id}/fuzzers/{fuzzer_id}/revisions/{revision_id}/actions/start', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Start Revision
     * @param {String} revisionId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    startRevision(revisionId, userId, projectId, fuzzerId) {
      return this.startRevisionWithHttpInfo(revisionId, userId, projectId, fuzzerId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Stop Revision
     * @param {String} revisionId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    stopRevisionWithHttpInfo(revisionId, userId, projectId, fuzzerId) {
      let postBody = null;
      // verify the required parameter 'revisionId' is set
      if (revisionId === undefined || revisionId === null) {
        throw new Error("Missing the required parameter 'revisionId' when calling stopRevision");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling stopRevision");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling stopRevision");
      }
      // verify the required parameter 'fuzzerId' is set
      if (fuzzerId === undefined || fuzzerId === null) {
        throw new Error("Missing the required parameter 'fuzzerId' when calling stopRevision");
      }

      let pathParams = {
        'revision_id': revisionId,
        'user_id': userId,
        'project_id': projectId,
        'fuzzer_id': fuzzerId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/users/{user_id}/projects/{project_id}/fuzzers/{fuzzer_id}/revisions/{revision_id}/actions/stop', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Stop Revision
     * @param {String} revisionId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    stopRevision(revisionId, userId, projectId, fuzzerId) {
      return this.stopRevisionWithHttpInfo(revisionId, userId, projectId, fuzzerId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update Revision Information
     * @param {String} revisionId 
     * @param {String} fuzzerId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {module:model/UpdateRevisionInfoRequestModel} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    updateRevisionInformationWithHttpInfo(revisionId, fuzzerId, userId, projectId, body) {
      let postBody = body;
      // verify the required parameter 'revisionId' is set
      if (revisionId === undefined || revisionId === null) {
        throw new Error("Missing the required parameter 'revisionId' when calling updateRevisionInformation");
      }
      // verify the required parameter 'fuzzerId' is set
      if (fuzzerId === undefined || fuzzerId === null) {
        throw new Error("Missing the required parameter 'fuzzerId' when calling updateRevisionInformation");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling updateRevisionInformation");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling updateRevisionInformation");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateRevisionInformation");
      }

      let pathParams = {
        'revision_id': revisionId,
        'fuzzer_id': fuzzerId,
        'user_id': userId,
        'project_id': projectId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/users/{user_id}/projects/{project_id}/fuzzers/{fuzzer_id}/revisions/{revision_id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update Revision Information
     * @param {String} revisionId 
     * @param {String} fuzzerId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {module:model/UpdateRevisionInfoRequestModel} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    updateRevisionInformation(revisionId, fuzzerId, userId, projectId, body) {
      return this.updateRevisionInformationWithHttpInfo(revisionId, fuzzerId, userId, projectId, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update Revision Resources
     * @param {String} fuzzerId 
     * @param {String} revisionId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {module:model/UpdateRevisionResourcesRequestModel} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    updateRevisionResourcesWithHttpInfo(fuzzerId, revisionId, userId, projectId, body) {
      let postBody = body;
      // verify the required parameter 'fuzzerId' is set
      if (fuzzerId === undefined || fuzzerId === null) {
        throw new Error("Missing the required parameter 'fuzzerId' when calling updateRevisionResources");
      }
      // verify the required parameter 'revisionId' is set
      if (revisionId === undefined || revisionId === null) {
        throw new Error("Missing the required parameter 'revisionId' when calling updateRevisionResources");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling updateRevisionResources");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling updateRevisionResources");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateRevisionResources");
      }

      let pathParams = {
        'fuzzer_id': fuzzerId,
        'revision_id': revisionId,
        'user_id': userId,
        'project_id': projectId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/users/{user_id}/projects/{project_id}/fuzzers/{fuzzer_id}/revisions/{revision_id}/resources', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update Revision Resources
     * @param {String} fuzzerId 
     * @param {String} revisionId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {module:model/UpdateRevisionResourcesRequestModel} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    updateRevisionResources(fuzzerId, revisionId, userId, projectId, body) {
      return this.updateRevisionResourcesWithHttpInfo(fuzzerId, revisionId, userId, projectId, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Upload Revision Binaries
     * @param {String} revisionId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @param {File} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    uploadRevisionBinariesWithHttpInfo(revisionId, userId, projectId, fuzzerId, body) {
      let postBody = body;
      // verify the required parameter 'revisionId' is set
      if (revisionId === undefined || revisionId === null) {
        throw new Error("Missing the required parameter 'revisionId' when calling uploadRevisionBinaries");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling uploadRevisionBinaries");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling uploadRevisionBinaries");
      }
      // verify the required parameter 'fuzzerId' is set
      if (fuzzerId === undefined || fuzzerId === null) {
        throw new Error("Missing the required parameter 'fuzzerId' when calling uploadRevisionBinaries");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling uploadRevisionBinaries");
      }

      let pathParams = {
        'revision_id': revisionId,
        'user_id': userId,
        'project_id': projectId,
        'fuzzer_id': fuzzerId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/octet-stream'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/users/{user_id}/projects/{project_id}/fuzzers/{fuzzer_id}/revisions/{revision_id}/files/binaries', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Upload Revision Binaries
     * @param {String} revisionId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @param {File} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    uploadRevisionBinaries(revisionId, userId, projectId, fuzzerId, body) {
      return this.uploadRevisionBinariesWithHttpInfo(revisionId, userId, projectId, fuzzerId, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Upload Revision Config
     * @param {String} revisionId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @param {File} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    uploadRevisionConfigWithHttpInfo(revisionId, userId, projectId, fuzzerId, body) {
      let postBody = body;
      // verify the required parameter 'revisionId' is set
      if (revisionId === undefined || revisionId === null) {
        throw new Error("Missing the required parameter 'revisionId' when calling uploadRevisionConfig");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling uploadRevisionConfig");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling uploadRevisionConfig");
      }
      // verify the required parameter 'fuzzerId' is set
      if (fuzzerId === undefined || fuzzerId === null) {
        throw new Error("Missing the required parameter 'fuzzerId' when calling uploadRevisionConfig");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling uploadRevisionConfig");
      }

      let pathParams = {
        'revision_id': revisionId,
        'user_id': userId,
        'project_id': projectId,
        'fuzzer_id': fuzzerId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/octet-stream'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/users/{user_id}/projects/{project_id}/fuzzers/{fuzzer_id}/revisions/{revision_id}/files/config', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Upload Revision Config
     * @param {String} revisionId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @param {File} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    uploadRevisionConfig(revisionId, userId, projectId, fuzzerId, body) {
      return this.uploadRevisionConfigWithHttpInfo(revisionId, userId, projectId, fuzzerId, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Upload Revision Seeds
     * @param {String} revisionId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @param {File} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    uploadRevisionSeedsWithHttpInfo(revisionId, userId, projectId, fuzzerId, body) {
      let postBody = body;
      // verify the required parameter 'revisionId' is set
      if (revisionId === undefined || revisionId === null) {
        throw new Error("Missing the required parameter 'revisionId' when calling uploadRevisionSeeds");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling uploadRevisionSeeds");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling uploadRevisionSeeds");
      }
      // verify the required parameter 'fuzzerId' is set
      if (fuzzerId === undefined || fuzzerId === null) {
        throw new Error("Missing the required parameter 'fuzzerId' when calling uploadRevisionSeeds");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling uploadRevisionSeeds");
      }

      let pathParams = {
        'revision_id': revisionId,
        'user_id': userId,
        'project_id': projectId,
        'fuzzer_id': fuzzerId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/octet-stream'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/users/{user_id}/projects/{project_id}/fuzzers/{fuzzer_id}/revisions/{revision_id}/files/seeds', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Upload Revision Seeds
     * @param {String} revisionId 
     * @param {String} userId 
     * @param {String} projectId 
     * @param {String} fuzzerId 
     * @param {File} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    uploadRevisionSeeds(revisionId, userId, projectId, fuzzerId, body) {
      return this.uploadRevisionSeedsWithHttpInfo(revisionId, userId, projectId, fuzzerId, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
