/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastApi.PoolResources();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PoolResources', function() {
    it('should create an instance of PoolResources', function() {
      // uncomment below and update the code to test PoolResources
      //var instance = new FastApi.PoolResources();
      //expect(instance).to.be.a(FastApi.PoolResources);
    });

    it('should have the property cpuAvail (base name: "cpu_avail")', function() {
      // uncomment below and update the code to test the property cpuAvail
      //var instance = new FastApi.PoolResources();
      //expect(instance).to.be();
    });

    it('should have the property cpuTotal (base name: "cpu_total")', function() {
      // uncomment below and update the code to test the property cpuTotal
      //var instance = new FastApi.PoolResources();
      //expect(instance).to.be();
    });

    it('should have the property fuzzerMaxCpu (base name: "fuzzer_max_cpu")', function() {
      // uncomment below and update the code to test the property fuzzerMaxCpu
      //var instance = new FastApi.PoolResources();
      //expect(instance).to.be();
    });

    it('should have the property fuzzerMaxRam (base name: "fuzzer_max_ram")', function() {
      // uncomment below and update the code to test the property fuzzerMaxRam
      //var instance = new FastApi.PoolResources();
      //expect(instance).to.be();
    });

    it('should have the property nodes (base name: "nodes")', function() {
      // uncomment below and update the code to test the property nodes
      //var instance = new FastApi.PoolResources();
      //expect(instance).to.be();
    });

    it('should have the property nodesAvail (base name: "nodes_avail")', function() {
      // uncomment below and update the code to test the property nodesAvail
      //var instance = new FastApi.PoolResources();
      //expect(instance).to.be();
    });

    it('should have the property nodesTotal (base name: "nodes_total")', function() {
      // uncomment below and update the code to test the property nodesTotal
      //var instance = new FastApi.PoolResources();
      //expect(instance).to.be();
    });

    it('should have the property ramAvail (base name: "ram_avail")', function() {
      // uncomment below and update the code to test the property ramAvail
      //var instance = new FastApi.PoolResources();
      //expect(instance).to.be();
    });

    it('should have the property ramTotal (base name: "ram_total")', function() {
      // uncomment below and update the code to test the property ramTotal
      //var instance = new FastApi.PoolResources();
      //expect(instance).to.be();
    });

  });

}));
