/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastApi.CrashesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CrashesApi', function() {
    describe('changeCrashArchived', function() {
      it('should call changeCrashArchived successfully', function(done) {
        //uncomment below and update the code to test changeCrashArchived
        //instance.changeCrashArchived(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('countFuzzerCrashes', function() {
      it('should call countFuzzerCrashes successfully', function(done) {
        //uncomment below and update the code to test countFuzzerCrashes
        //instance.countFuzzerCrashes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('countRevisionCrashes', function() {
      it('should call countRevisionCrashes successfully', function(done) {
        //uncomment below and update the code to test countRevisionCrashes
        //instance.countRevisionCrashes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('downloadFuzzerCrash', function() {
      it('should call downloadFuzzerCrash successfully', function(done) {
        //uncomment below and update the code to test downloadFuzzerCrash
        //instance.downloadFuzzerCrash(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFuzzerCrash', function() {
      it('should call getFuzzerCrash successfully', function(done) {
        //uncomment below and update the code to test getFuzzerCrash
        //instance.getFuzzerCrash(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listFuzzerCrashes', function() {
      it('should call listFuzzerCrashes successfully', function(done) {
        //uncomment below and update the code to test listFuzzerCrashes
        //instance.listFuzzerCrashes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listRevisionCrashes', function() {
      it('should call listRevisionCrashes successfully', function(done) {
        //uncomment below and update the code to test listRevisionCrashes
        //instance.listRevisionCrashes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
