/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastApi.EnginesAdminApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EnginesAdminApi', function() {
    describe('createEngine', function() {
      it('should call createEngine successfully', function(done) {
        //uncomment below and update the code to test createEngine
        //instance.createEngine(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteEngine', function() {
      it('should call deleteEngine successfully', function(done) {
        //uncomment below and update the code to test deleteEngine
        //instance.deleteEngine(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('disableEngineLang', function() {
      it('should call disableEngineLang successfully', function(done) {
        //uncomment below and update the code to test disableEngineLang
        //instance.disableEngineLang(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('enableEngineLang', function() {
      it('should call enableEngineLang successfully', function(done) {
        //uncomment below and update the code to test enableEngineLang
        //instance.enableEngineLang(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEngine', function() {
      it('should call getEngine successfully', function(done) {
        //uncomment below and update the code to test getEngine
        //instance.getEngine(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listEngines', function() {
      it('should call listEngines successfully', function(done) {
        //uncomment below and update the code to test listEngines
        //instance.listEngines(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setEngineLangs', function() {
      it('should call setEngineLangs successfully', function(done) {
        //uncomment below and update the code to test setEngineLangs
        //instance.setEngineLangs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateEngine', function() {
      it('should call updateEngine successfully', function(done) {
        //uncomment below and update the code to test updateEngine
        //instance.updateEngine(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
