/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastApi.PoolsAdminApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PoolsAdminApi', function() {
    describe('adminCreatePool', function() {
      it('should call adminCreatePool successfully', function(done) {
        //uncomment below and update the code to test adminCreatePool
        //instance.adminCreatePool(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('adminDeletePool', function() {
      it('should call adminDeletePool successfully', function(done) {
        //uncomment below and update the code to test adminDeletePool
        //instance.adminDeletePool(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('adminGetPool', function() {
      it('should call adminGetPool successfully', function(done) {
        //uncomment below and update the code to test adminGetPool
        //instance.adminGetPool(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('adminGetPoolsCount', function() {
      it('should call adminGetPoolsCount successfully', function(done) {
        //uncomment below and update the code to test adminGetPoolsCount
        //instance.adminGetPoolsCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('adminListPools', function() {
      it('should call adminListPools successfully', function(done) {
        //uncomment below and update the code to test adminListPools
        //instance.adminListPools(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('adminUpdatePoolInfo', function() {
      it('should call adminUpdatePoolInfo successfully', function(done) {
        //uncomment below and update the code to test adminUpdatePoolInfo
        //instance.adminUpdatePoolInfo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('adminUpdatePoolNodeGroup', function() {
      it('should call adminUpdatePoolNodeGroup successfully', function(done) {
        //uncomment below and update the code to test adminUpdatePoolNodeGroup
        //instance.adminUpdatePoolNodeGroup(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
