/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastApi.UsersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsersApi', function() {
    describe('changeBugTrackerIntegrationEnabled', function() {
      it('should call changeBugTrackerIntegrationEnabled successfully', function(done) {
        //uncomment below and update the code to test changeBugTrackerIntegrationEnabled
        //instance.changeBugTrackerIntegrationEnabled(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('changeCrashArchived', function() {
      it('should call changeCrashArchived successfully', function(done) {
        //uncomment below and update the code to test changeCrashArchived
        //instance.changeCrashArchived(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('copyCorpusFiles', function() {
      it('should call copyCorpusFiles successfully', function(done) {
        //uncomment below and update the code to test copyCorpusFiles
        //instance.copyCorpusFiles(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('countFuzzerCrashes', function() {
      it('should call countFuzzerCrashes successfully', function(done) {
        //uncomment below and update the code to test countFuzzerCrashes
        //instance.countFuzzerCrashes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('countFuzzerStatisticsRecords', function() {
      it('should call countFuzzerStatisticsRecords successfully', function(done) {
        //uncomment below and update the code to test countFuzzerStatisticsRecords
        //instance.countFuzzerStatisticsRecords(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('countProjectImages', function() {
      it('should call countProjectImages successfully', function(done) {
        //uncomment below and update the code to test countProjectImages
        //instance.countProjectImages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('countRevisionCrashes', function() {
      it('should call countRevisionCrashes successfully', function(done) {
        //uncomment below and update the code to test countRevisionCrashes
        //instance.countRevisionCrashes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('countRevisionStatisticsRecords', function() {
      it('should call countRevisionStatisticsRecords successfully', function(done) {
        //uncomment below and update the code to test countRevisionStatisticsRecords
        //instance.countRevisionStatisticsRecords(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createBugTrackerIntegration', function() {
      it('should call createBugTrackerIntegration successfully', function(done) {
        //uncomment below and update the code to test createBugTrackerIntegration
        //instance.createBugTrackerIntegration(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createFuzzer', function() {
      it('should call createFuzzer successfully', function(done) {
        //uncomment below and update the code to test createFuzzer
        //instance.createFuzzer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createProject', function() {
      it('should call createProject successfully', function(done) {
        //uncomment below and update the code to test createProject
        //instance.createProject(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createProjectPool', function() {
      it('should call createProjectPool successfully', function(done) {
        //uncomment below and update the code to test createProjectPool
        //instance.createProjectPool(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createRevision', function() {
      it('should call createRevision successfully', function(done) {
        //uncomment below and update the code to test createRevision
        //instance.createRevision(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteFuzzer', function() {
      it('should call deleteFuzzer successfully', function(done) {
        //uncomment below and update the code to test deleteFuzzer
        //instance.deleteFuzzer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteIntegration', function() {
      it('should call deleteIntegration successfully', function(done) {
        //uncomment below and update the code to test deleteIntegration
        //instance.deleteIntegration(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteProject', function() {
      it('should call deleteProject successfully', function(done) {
        //uncomment below and update the code to test deleteProject
        //instance.deleteProject(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteProjectPool', function() {
      it('should call deleteProjectPool successfully', function(done) {
        //uncomment below and update the code to test deleteProjectPool
        //instance.deleteProjectPool(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteRevision', function() {
      it('should call deleteRevision successfully', function(done) {
        //uncomment below and update the code to test deleteRevision
        //instance.deleteRevision(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('downloadFuzzerCorpus', function() {
      it('should call downloadFuzzerCorpus successfully', function(done) {
        //uncomment below and update the code to test downloadFuzzerCorpus
        //instance.downloadFuzzerCorpus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('downloadFuzzerCrash', function() {
      it('should call downloadFuzzerCrash successfully', function(done) {
        //uncomment below and update the code to test downloadFuzzerCrash
        //instance.downloadFuzzerCrash(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('downloadRevisionBinaries', function() {
      it('should call downloadRevisionBinaries successfully', function(done) {
        //uncomment below and update the code to test downloadRevisionBinaries
        //instance.downloadRevisionBinaries(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('downloadRevisionConfig', function() {
      it('should call downloadRevisionConfig successfully', function(done) {
        //uncomment below and update the code to test downloadRevisionConfig
        //instance.downloadRevisionConfig(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('downloadRevisionSeeds', function() {
      it('should call downloadRevisionSeeds successfully', function(done) {
        //uncomment below and update the code to test downloadRevisionSeeds
        //instance.downloadRevisionSeeds(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('emptyProjectTrashbin', function() {
      it('should call emptyProjectTrashbin successfully', function(done) {
        //uncomment below and update the code to test emptyProjectTrashbin
        //instance.emptyProjectTrashbin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('emptyUserTrashbin', function() {
      it('should call emptyUserTrashbin successfully', function(done) {
        //uncomment below and update the code to test emptyUserTrashbin
        //instance.emptyUserTrashbin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eraseFuzzerInTrashbin', function() {
      it('should call eraseFuzzerInTrashbin successfully', function(done) {
        //uncomment below and update the code to test eraseFuzzerInTrashbin
        //instance.eraseFuzzerInTrashbin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActiveRevision', function() {
      it('should call getActiveRevision successfully', function(done) {
        //uncomment below and update the code to test getActiveRevision
        //instance.getActiveRevision(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBugTrackerIntegration', function() {
      it('should call getBugTrackerIntegration successfully', function(done) {
        //uncomment below and update the code to test getBugTrackerIntegration
        //instance.getBugTrackerIntegration(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBugTrackerIntegrationByName', function() {
      it('should call getBugTrackerIntegrationByName successfully', function(done) {
        //uncomment below and update the code to test getBugTrackerIntegrationByName
        //instance.getBugTrackerIntegrationByName(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBugTrackerIntegrationConfig', function() {
      it('should call getBugTrackerIntegrationConfig successfully', function(done) {
        //uncomment below and update the code to test getBugTrackerIntegrationConfig
        //instance.getBugTrackerIntegrationConfig(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCountOfBugTrackerIntegrations', function() {
      it('should call getCountOfBugTrackerIntegrations successfully', function(done) {
        //uncomment below and update the code to test getCountOfBugTrackerIntegrations
        //instance.getCountOfBugTrackerIntegrations(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFuzzer', function() {
      it('should call getFuzzer successfully', function(done) {
        //uncomment below and update the code to test getFuzzer
        //instance.getFuzzer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFuzzerByName', function() {
      it('should call getFuzzerByName successfully', function(done) {
        //uncomment below and update the code to test getFuzzerByName
        //instance.getFuzzerByName(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFuzzerCount', function() {
      it('should call getFuzzerCount successfully', function(done) {
        //uncomment below and update the code to test getFuzzerCount
        //instance.getFuzzerCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFuzzerCrash', function() {
      it('should call getFuzzerCrash successfully', function(done) {
        //uncomment below and update the code to test getFuzzerCrash
        //instance.getFuzzerCrash(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProject', function() {
      it('should call getProject successfully', function(done) {
        //uncomment below and update the code to test getProject
        //instance.getProject(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProjectByName', function() {
      it('should call getProjectByName successfully', function(done) {
        //uncomment below and update the code to test getProjectByName
        //instance.getProjectByName(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProjectCount', function() {
      it('should call getProjectCount successfully', function(done) {
        //uncomment below and update the code to test getProjectCount
        //instance.getProjectCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProjectImage', function() {
      it('should call getProjectImage successfully', function(done) {
        //uncomment below and update the code to test getProjectImage
        //instance.getProjectImage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProjectPool', function() {
      it('should call getProjectPool successfully', function(done) {
        //uncomment below and update the code to test getProjectPool
        //instance.getProjectPool(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRevision', function() {
      it('should call getRevision successfully', function(done) {
        //uncomment below and update the code to test getRevision
        //instance.getRevision(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRevisionByName', function() {
      it('should call getRevisionByName successfully', function(done) {
        //uncomment below and update the code to test getRevisionByName
        //instance.getRevisionByName(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRevisionCount', function() {
      it('should call getRevisionCount successfully', function(done) {
        //uncomment below and update the code to test getRevisionCount
        //instance.getRevisionCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSelfUser', function() {
      it('should call getSelfUser successfully', function(done) {
        //uncomment below and update the code to test getSelfUser
        //instance.getSelfUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTrashbinFuzzersCount', function() {
      it('should call getTrashbinFuzzersCount successfully', function(done) {
        //uncomment below and update the code to test getTrashbinFuzzersCount
        //instance.getTrashbinFuzzersCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listFuzzerCrashes', function() {
      it('should call listFuzzerCrashes successfully', function(done) {
        //uncomment below and update the code to test listFuzzerCrashes
        //instance.listFuzzerCrashes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listFuzzerStatistics', function() {
      it('should call listFuzzerStatistics successfully', function(done) {
        //uncomment below and update the code to test listFuzzerStatistics
        //instance.listFuzzerStatistics(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listFuzzers', function() {
      it('should call listFuzzers successfully', function(done) {
        //uncomment below and update the code to test listFuzzers
        //instance.listFuzzers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listIntegrations', function() {
      it('should call listIntegrations successfully', function(done) {
        //uncomment below and update the code to test listIntegrations
        //instance.listIntegrations(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listPoolsGetLoad', function() {
      it('should call listPoolsGetLoad successfully', function(done) {
        //uncomment below and update the code to test listPoolsGetLoad
        //instance.listPoolsGetLoad(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listProjectImages', function() {
      it('should call listProjectImages successfully', function(done) {
        //uncomment below and update the code to test listProjectImages
        //instance.listProjectImages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listProjects', function() {
      it('should call listProjects successfully', function(done) {
        //uncomment below and update the code to test listProjects
        //instance.listProjects(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listRevisionCrashes', function() {
      it('should call listRevisionCrashes successfully', function(done) {
        //uncomment below and update the code to test listRevisionCrashes
        //instance.listRevisionCrashes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listRevisionStatistics', function() {
      it('should call listRevisionStatistics successfully', function(done) {
        //uncomment below and update the code to test listRevisionStatistics
        //instance.listRevisionStatistics(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listRevisions', function() {
      it('should call listRevisions successfully', function(done) {
        //uncomment below and update the code to test listRevisions
        //instance.listRevisions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listTrashbinFuzzers', function() {
      it('should call listTrashbinFuzzers successfully', function(done) {
        //uncomment below and update the code to test listTrashbinFuzzers
        //instance.listTrashbinFuzzers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('restartFuzzer', function() {
      it('should call restartFuzzer successfully', function(done) {
        //uncomment below and update the code to test restartFuzzer
        //instance.restartFuzzer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('restartRevision', function() {
      it('should call restartRevision successfully', function(done) {
        //uncomment below and update the code to test restartRevision
        //instance.restartRevision(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setActiveRevision', function() {
      it('should call setActiveRevision successfully', function(done) {
        //uncomment below and update the code to test setActiveRevision
        //instance.setActiveRevision(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setProjectPoolExpireDate', function() {
      it('should call setProjectPoolExpireDate successfully', function(done) {
        //uncomment below and update the code to test setProjectPoolExpireDate
        //instance.setProjectPoolExpireDate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('startFuzzer', function() {
      it('should call startFuzzer successfully', function(done) {
        //uncomment below and update the code to test startFuzzer
        //instance.startFuzzer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('startRevision', function() {
      it('should call startRevision successfully', function(done) {
        //uncomment below and update the code to test startRevision
        //instance.startRevision(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('stopFuzzer', function() {
      it('should call stopFuzzer successfully', function(done) {
        //uncomment below and update the code to test stopFuzzer
        //instance.stopFuzzer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('stopRevision', function() {
      it('should call stopRevision successfully', function(done) {
        //uncomment below and update the code to test stopRevision
        //instance.stopRevision(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('unsetProjectPoolExpireDate', function() {
      it('should call unsetProjectPoolExpireDate successfully', function(done) {
        //uncomment below and update the code to test unsetProjectPoolExpireDate
        //instance.unsetProjectPoolExpireDate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateBugTrackerIntegration', function() {
      it('should call updateBugTrackerIntegration successfully', function(done) {
        //uncomment below and update the code to test updateBugTrackerIntegration
        //instance.updateBugTrackerIntegration(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateBugTrackerIntegrationConfig', function() {
      it('should call updateBugTrackerIntegrationConfig successfully', function(done) {
        //uncomment below and update the code to test updateBugTrackerIntegrationConfig
        //instance.updateBugTrackerIntegrationConfig(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateFuzzer', function() {
      it('should call updateFuzzer successfully', function(done) {
        //uncomment below and update the code to test updateFuzzer
        //instance.updateFuzzer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateProject', function() {
      it('should call updateProject successfully', function(done) {
        //uncomment below and update the code to test updateProject
        //instance.updateProject(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateProjectPool', function() {
      it('should call updateProjectPool successfully', function(done) {
        //uncomment below and update the code to test updateProjectPool
        //instance.updateProjectPool(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateRevisionInformation', function() {
      it('should call updateRevisionInformation successfully', function(done) {
        //uncomment below and update the code to test updateRevisionInformation
        //instance.updateRevisionInformation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateRevisionResources', function() {
      it('should call updateRevisionResources successfully', function(done) {
        //uncomment below and update the code to test updateRevisionResources
        //instance.updateRevisionResources(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateSelfUser', function() {
      it('should call updateSelfUser successfully', function(done) {
        //uncomment below and update the code to test updateSelfUser
        //instance.updateSelfUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('uploadRevisionBinaries', function() {
      it('should call uploadRevisionBinaries successfully', function(done) {
        //uncomment below and update the code to test uploadRevisionBinaries
        //instance.uploadRevisionBinaries(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('uploadRevisionConfig', function() {
      it('should call uploadRevisionConfig successfully', function(done) {
        //uncomment below and update the code to test uploadRevisionConfig
        //instance.uploadRevisionConfig(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('uploadRevisionSeeds', function() {
      it('should call uploadRevisionSeeds successfully', function(done) {
        //uncomment below and update the code to test uploadRevisionSeeds
        //instance.uploadRevisionSeeds(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
