/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiGatewayAppApiAdminUsersUpdateUserRequestModel model module.
 * @module model/ApiGatewayAppApiAdminUsersUpdateUserRequestModel
 * @version 0.1.0
 */
class ApiGatewayAppApiAdminUsersUpdateUserRequestModel {
    /**
     * Constructs a new <code>ApiGatewayAppApiAdminUsersUpdateUserRequestModel</code>.
     * @alias module:model/ApiGatewayAppApiAdminUsersUpdateUserRequestModel
     */
    constructor() { 
        
        ApiGatewayAppApiAdminUsersUpdateUserRequestModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiGatewayAppApiAdminUsersUpdateUserRequestModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiGatewayAppApiAdminUsersUpdateUserRequestModel} obj Optional instance to populate.
     * @return {module:model/ApiGatewayAppApiAdminUsersUpdateUserRequestModel} The populated <code>ApiGatewayAppApiAdminUsersUpdateUserRequestModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiGatewayAppApiAdminUsersUpdateUserRequestModel();

            if (data.hasOwnProperty('display_name')) {
                obj['display_name'] = ApiClient.convertToType(data['display_name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('is_confirmed')) {
                obj['is_confirmed'] = ApiClient.convertToType(data['is_confirmed'], 'Boolean');
            }
            if (data.hasOwnProperty('is_disabled')) {
                obj['is_disabled'] = ApiClient.convertToType(data['is_disabled'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} display_name
 */
ApiGatewayAppApiAdminUsersUpdateUserRequestModel.prototype['display_name'] = undefined;

/**
 * @member {String} email
 */
ApiGatewayAppApiAdminUsersUpdateUserRequestModel.prototype['email'] = undefined;

/**
 * @member {Boolean} is_confirmed
 */
ApiGatewayAppApiAdminUsersUpdateUserRequestModel.prototype['is_confirmed'] = undefined;

/**
 * @member {Boolean} is_disabled
 */
ApiGatewayAppApiAdminUsersUpdateUserRequestModel.prototype['is_disabled'] = undefined;

/**
 * @member {String} name
 */
ApiGatewayAppApiAdminUsersUpdateUserRequestModel.prototype['name'] = undefined;

/**
 * @member {String} password
 */
ApiGatewayAppApiAdminUsersUpdateUserRequestModel.prototype['password'] = undefined;






export default ApiGatewayAppApiAdminUsersUpdateUserRequestModel;

