/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CloudNodeGroupModel model module.
 * @module model/CloudNodeGroupModel
 * @version 0.1.0
 */
class CloudNodeGroupModel {
    /**
     * Constructs a new <code>CloudNodeGroupModel</code>.
     * @alias module:model/CloudNodeGroupModel
     * @param nodeCount {Number} 
     * @param nodeCpu {Number} 
     * @param nodeRam {Number} 
     */
    constructor(nodeCount, nodeCpu, nodeRam) { 
        
        CloudNodeGroupModel.initialize(this, nodeCount, nodeCpu, nodeRam);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, nodeCount, nodeCpu, nodeRam) { 
        obj['node_count'] = nodeCount;
        obj['node_cpu'] = nodeCpu;
        obj['node_ram'] = nodeRam;
    }

    /**
     * Constructs a <code>CloudNodeGroupModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CloudNodeGroupModel} obj Optional instance to populate.
     * @return {module:model/CloudNodeGroupModel} The populated <code>CloudNodeGroupModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CloudNodeGroupModel();

            if (data.hasOwnProperty('node_count')) {
                obj['node_count'] = ApiClient.convertToType(data['node_count'], 'Number');
            }
            if (data.hasOwnProperty('node_cpu')) {
                obj['node_cpu'] = ApiClient.convertToType(data['node_cpu'], 'Number');
            }
            if (data.hasOwnProperty('node_ram')) {
                obj['node_ram'] = ApiClient.convertToType(data['node_ram'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} node_count
 */
CloudNodeGroupModel.prototype['node_count'] = undefined;

/**
 * @member {Number} node_cpu
 */
CloudNodeGroupModel.prototype['node_cpu'] = undefined;

/**
 * @member {Number} node_ram
 */
CloudNodeGroupModel.prototype['node_ram'] = undefined;






export default CloudNodeGroupModel;

