/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ORMEngineID from './ORMEngineID';

/**
 * The CreateImageResponseModel model module.
 * @module model/CreateImageResponseModel
 * @version 0.1.0
 */
class CreateImageResponseModel {
    /**
     * Constructs a new <code>CreateImageResponseModel</code>.
     * @alias module:model/CreateImageResponseModel
     * @param description {String} 
     * @param engines {Array.<module:model/ORMEngineID>} 
     * @param id {String} 
     * @param name {String} 
     * @param status {String} 
     */
    constructor(description, engines, id, name, status) { 
        
        CreateImageResponseModel.initialize(this, description, engines, id, name, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, description, engines, id, name, status) { 
        obj['description'] = description;
        obj['engines'] = engines;
        obj['id'] = id;
        obj['name'] = name;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>CreateImageResponseModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateImageResponseModel} obj Optional instance to populate.
     * @return {module:model/CreateImageResponseModel} The populated <code>CreateImageResponseModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateImageResponseModel();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('engines')) {
                obj['engines'] = ApiClient.convertToType(data['engines'], [ORMEngineID]);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} description
 */
CreateImageResponseModel.prototype['description'] = undefined;

/**
 * @member {Array.<module:model/ORMEngineID>} engines
 */
CreateImageResponseModel.prototype['engines'] = undefined;

/**
 * @member {String} id
 */
CreateImageResponseModel.prototype['id'] = undefined;

/**
 * @member {String} name
 */
CreateImageResponseModel.prototype['name'] = undefined;

/**
 * @member {String} status
 */
CreateImageResponseModel.prototype['status'] = undefined;






export default CreateImageResponseModel;

