/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateRevisionRequestModel model module.
 * @module model/CreateRevisionRequestModel
 * @version 0.1.0
 */
class CreateRevisionRequestModel {
    /**
     * Constructs a new <code>CreateRevisionRequestModel</code>.
     * @alias module:model/CreateRevisionRequestModel
     * @param cpuUsage {Number} 
     * @param description {String} 
     * @param imageId {String} 
     * @param ramUsage {Number} 
     * @param tmpfsSize {Number} 
     */
    constructor(cpuUsage, description, imageId, ramUsage, tmpfsSize) { 
        
        CreateRevisionRequestModel.initialize(this, cpuUsage, description, imageId, ramUsage, tmpfsSize);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cpuUsage, description, imageId, ramUsage, tmpfsSize) { 
        obj['cpu_usage'] = cpuUsage;
        obj['description'] = description;
        obj['image_id'] = imageId;
        obj['ram_usage'] = ramUsage;
        obj['tmpfs_size'] = tmpfsSize;
    }

    /**
     * Constructs a <code>CreateRevisionRequestModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateRevisionRequestModel} obj Optional instance to populate.
     * @return {module:model/CreateRevisionRequestModel} The populated <code>CreateRevisionRequestModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateRevisionRequestModel();

            if (data.hasOwnProperty('cpu_usage')) {
                obj['cpu_usage'] = ApiClient.convertToType(data['cpu_usage'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('image_id')) {
                obj['image_id'] = ApiClient.convertToType(data['image_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('ram_usage')) {
                obj['ram_usage'] = ApiClient.convertToType(data['ram_usage'], 'Number');
            }
            if (data.hasOwnProperty('tmpfs_size')) {
                obj['tmpfs_size'] = ApiClient.convertToType(data['tmpfs_size'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} cpu_usage
 */
CreateRevisionRequestModel.prototype['cpu_usage'] = undefined;

/**
 * @member {String} description
 */
CreateRevisionRequestModel.prototype['description'] = undefined;

/**
 * @member {String} image_id
 */
CreateRevisionRequestModel.prototype['image_id'] = undefined;

/**
 * @member {String} name
 */
CreateRevisionRequestModel.prototype['name'] = undefined;

/**
 * @member {Number} ram_usage
 */
CreateRevisionRequestModel.prototype['ram_usage'] = undefined;

/**
 * @member {Number} tmpfs_size
 */
CreateRevisionRequestModel.prototype['tmpfs_size'] = undefined;






export default CreateRevisionRequestModel;

