/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ORMEngineID from './ORMEngineID';
import ORMLangID from './ORMLangID';

/**
 * The CreateFuzzerRequestModel model module.
 * @module model/CreateFuzzerRequestModel
 * @version 0.1.0
 */
class CreateFuzzerRequestModel {
    /**
     * Constructs a new <code>CreateFuzzerRequestModel</code>.
     * @alias module:model/CreateFuzzerRequestModel
     * @param ciIntegration {Boolean} 
     * @param description {String} 
     * @param engine {module:model/ORMEngineID} 
     * @param lang {module:model/ORMLangID} 
     * @param name {String} 
     */
    constructor(ciIntegration, description, engine, lang, name) { 
        
        CreateFuzzerRequestModel.initialize(this, ciIntegration, description, engine, lang, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, ciIntegration, description, engine, lang, name) { 
        obj['ci_integration'] = ciIntegration;
        obj['description'] = description;
        obj['engine'] = engine;
        obj['lang'] = lang;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>CreateFuzzerRequestModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateFuzzerRequestModel} obj Optional instance to populate.
     * @return {module:model/CreateFuzzerRequestModel} The populated <code>CreateFuzzerRequestModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateFuzzerRequestModel();

            if (data.hasOwnProperty('ci_integration')) {
                obj['ci_integration'] = ApiClient.convertToType(data['ci_integration'], 'Boolean');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('engine')) {
                obj['engine'] = ORMEngineID.constructFromObject(data['engine']);
            }
            if (data.hasOwnProperty('lang')) {
                obj['lang'] = ORMLangID.constructFromObject(data['lang']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} ci_integration
 */
CreateFuzzerRequestModel.prototype['ci_integration'] = undefined;

/**
 * @member {String} description
 */
CreateFuzzerRequestModel.prototype['description'] = undefined;

/**
 * @member {module:model/ORMEngineID} engine
 */
CreateFuzzerRequestModel.prototype['engine'] = undefined;

/**
 * @member {module:model/ORMLangID} lang
 */
CreateFuzzerRequestModel.prototype['lang'] = undefined;

/**
 * @member {String} name
 */
CreateFuzzerRequestModel.prototype['name'] = undefined;






export default CreateFuzzerRequestModel;

