/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FuzzerConfigResponseModel model module.
 * @module model/FuzzerConfigResponseModel
 * @version 0.1.0
 */
class FuzzerConfigResponseModel {
    /**
     * Constructs a new <code>FuzzerConfigResponseModel</code>.
     * @alias module:model/FuzzerConfigResponseModel
     * @param minCpuUsage {Number} 
     * @param minRamUsage {Number} 
     * @param minTmpfsUsage {Number} 
     */
    constructor(minCpuUsage, minRamUsage, minTmpfsUsage) { 
        
        FuzzerConfigResponseModel.initialize(this, minCpuUsage, minRamUsage, minTmpfsUsage);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, minCpuUsage, minRamUsage, minTmpfsUsage) { 
        obj['min_cpu_usage'] = minCpuUsage;
        obj['min_ram_usage'] = minRamUsage;
        obj['min_tmpfs_usage'] = minTmpfsUsage;
    }

    /**
     * Constructs a <code>FuzzerConfigResponseModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FuzzerConfigResponseModel} obj Optional instance to populate.
     * @return {module:model/FuzzerConfigResponseModel} The populated <code>FuzzerConfigResponseModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FuzzerConfigResponseModel();

            if (data.hasOwnProperty('min_cpu_usage')) {
                obj['min_cpu_usage'] = ApiClient.convertToType(data['min_cpu_usage'], 'Number');
            }
            if (data.hasOwnProperty('min_ram_usage')) {
                obj['min_ram_usage'] = ApiClient.convertToType(data['min_ram_usage'], 'Number');
            }
            if (data.hasOwnProperty('min_tmpfs_usage')) {
                obj['min_tmpfs_usage'] = ApiClient.convertToType(data['min_tmpfs_usage'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} min_cpu_usage
 */
FuzzerConfigResponseModel.prototype['min_cpu_usage'] = undefined;

/**
 * @member {Number} min_ram_usage
 */
FuzzerConfigResponseModel.prototype['min_ram_usage'] = undefined;

/**
 * @member {Number} min_tmpfs_usage
 */
FuzzerConfigResponseModel.prototype['min_tmpfs_usage'] = undefined;






export default FuzzerConfigResponseModel;

