/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetRevisionResponseModel from './GetRevisionResponseModel';
import ORMEngineID from './ORMEngineID';
import ORMLangID from './ORMLangID';

/**
 * The GetFuzzerResponseModel model module.
 * @module model/GetFuzzerResponseModel
 * @version 0.1.0
 */
class GetFuzzerResponseModel {
    /**
     * Constructs a new <code>GetFuzzerResponseModel</code>.
     * @alias module:model/GetFuzzerResponseModel
     * @param ciIntegration {Boolean} 
     * @param description {String} 
     * @param engine {module:model/ORMEngineID} 
     * @param id {String} 
     * @param lang {module:model/ORMLangID} 
     * @param name {String} 
     */
    constructor(ciIntegration, description, engine, id, lang, name) { 
        
        GetFuzzerResponseModel.initialize(this, ciIntegration, description, engine, id, lang, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, ciIntegration, description, engine, id, lang, name) { 
        obj['ci_integration'] = ciIntegration;
        obj['description'] = description;
        obj['engine'] = engine;
        obj['id'] = id;
        obj['lang'] = lang;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>GetFuzzerResponseModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetFuzzerResponseModel} obj Optional instance to populate.
     * @return {module:model/GetFuzzerResponseModel} The populated <code>GetFuzzerResponseModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetFuzzerResponseModel();

            if (data.hasOwnProperty('active_revision')) {
                obj['active_revision'] = GetRevisionResponseModel.constructFromObject(data['active_revision']);
            }
            if (data.hasOwnProperty('ci_integration')) {
                obj['ci_integration'] = ApiClient.convertToType(data['ci_integration'], 'Boolean');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('engine')) {
                obj['engine'] = ORMEngineID.constructFromObject(data['engine']);
            }
            if (data.hasOwnProperty('erasure_date')) {
                obj['erasure_date'] = ApiClient.convertToType(data['erasure_date'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('lang')) {
                obj['lang'] = ORMLangID.constructFromObject(data['lang']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/GetRevisionResponseModel} active_revision
 */
GetFuzzerResponseModel.prototype['active_revision'] = undefined;

/**
 * @member {Boolean} ci_integration
 */
GetFuzzerResponseModel.prototype['ci_integration'] = undefined;

/**
 * @member {String} description
 */
GetFuzzerResponseModel.prototype['description'] = undefined;

/**
 * @member {module:model/ORMEngineID} engine
 */
GetFuzzerResponseModel.prototype['engine'] = undefined;

/**
 * @member {String} erasure_date
 */
GetFuzzerResponseModel.prototype['erasure_date'] = undefined;

/**
 * @member {String} id
 */
GetFuzzerResponseModel.prototype['id'] = undefined;

/**
 * @member {module:model/ORMLangID} lang
 */
GetFuzzerResponseModel.prototype['lang'] = undefined;

/**
 * @member {String} name
 */
GetFuzzerResponseModel.prototype['name'] = undefined;






export default GetFuzzerResponseModel;

