/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HTTPValidationError model module.
 * @module model/HTTPValidationError
 * @version 0.1.0
 */
class HTTPValidationError {
    /**
     * Constructs a new <code>HTTPValidationError</code>.
     * @alias module:model/HTTPValidationError
     * @param code {String} 
     * @param message {String} 
     */
    constructor(code, message) { 
        
        HTTPValidationError.initialize(this, code, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code, message) { 
        obj['code'] = code;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>HTTPValidationError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HTTPValidationError} obj Optional instance to populate.
     * @return {module:model/HTTPValidationError} The populated <code>HTTPValidationError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HTTPValidationError();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('params')) {
                obj['params'] = ApiClient.convertToType(data['params'], [Object]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} code
 */
HTTPValidationError.prototype['code'] = undefined;

/**
 * @member {String} message
 */
HTTPValidationError.prototype['message'] = undefined;

/**
 * @member {Array.<Object>} params
 */
HTTPValidationError.prototype['params'] = undefined;






export default HTTPValidationError;

