/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ORMIntegrationTypeID from './ORMIntegrationTypeID';

/**
 * The IntegrationTypeResponseModel model module.
 * @module model/IntegrationTypeResponseModel
 * @version 0.1.0
 */
class IntegrationTypeResponseModel {
    /**
     * Constructs a new <code>IntegrationTypeResponseModel</code>.
     * @alias module:model/IntegrationTypeResponseModel
     * @param displayName {String} 
     * @param id {module:model/ORMIntegrationTypeID} 
     * @param twoway {Boolean} 
     */
    constructor(displayName, id, twoway) { 
        
        IntegrationTypeResponseModel.initialize(this, displayName, id, twoway);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, displayName, id, twoway) { 
        obj['display_name'] = displayName;
        obj['id'] = id;
        obj['twoway'] = twoway;
    }

    /**
     * Constructs a <code>IntegrationTypeResponseModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IntegrationTypeResponseModel} obj Optional instance to populate.
     * @return {module:model/IntegrationTypeResponseModel} The populated <code>IntegrationTypeResponseModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IntegrationTypeResponseModel();

            if (data.hasOwnProperty('display_name')) {
                obj['display_name'] = ApiClient.convertToType(data['display_name'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ORMIntegrationTypeID.constructFromObject(data['id']);
            }
            if (data.hasOwnProperty('twoway')) {
                obj['twoway'] = ApiClient.convertToType(data['twoway'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} display_name
 */
IntegrationTypeResponseModel.prototype['display_name'] = undefined;

/**
 * @member {module:model/ORMIntegrationTypeID} id
 */
IntegrationTypeResponseModel.prototype['id'] = undefined;

/**
 * @member {Boolean} twoway
 */
IntegrationTypeResponseModel.prototype['twoway'] = undefined;






export default IntegrationTypeResponseModel;

