/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The JiraIntegrationConfigResponseModel model module.
 * @module model/JiraIntegrationConfigResponseModel
 * @version 0.1.0
 */
class JiraIntegrationConfigResponseModel {
    /**
     * Constructs a new <code>JiraIntegrationConfigResponseModel</code>.
     * @alias module:model/JiraIntegrationConfigResponseModel
     * @param id {String} 
     * @param issueType {String} 
     * @param password {String} 
     * @param project {String} 
     * @param url {String} 
     * @param username {String} 
     */
    constructor(id, issueType, password, project, url, username) { 
        
        JiraIntegrationConfigResponseModel.initialize(this, id, issueType, password, project, url, username);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, issueType, password, project, url, username) { 
        obj['id'] = id;
        obj['issue_type'] = issueType;
        obj['password'] = password;
        obj['project'] = project;
        obj['url'] = url;
        obj['username'] = username;
    }

    /**
     * Constructs a <code>JiraIntegrationConfigResponseModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JiraIntegrationConfigResponseModel} obj Optional instance to populate.
     * @return {module:model/JiraIntegrationConfigResponseModel} The populated <code>JiraIntegrationConfigResponseModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JiraIntegrationConfigResponseModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('issue_type')) {
                obj['issue_type'] = ApiClient.convertToType(data['issue_type'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'String');
            }
            if (data.hasOwnProperty('project')) {
                obj['project'] = ApiClient.convertToType(data['project'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
JiraIntegrationConfigResponseModel.prototype['id'] = undefined;

/**
 * @member {String} issue_type
 */
JiraIntegrationConfigResponseModel.prototype['issue_type'] = undefined;

/**
 * @member {String} password
 */
JiraIntegrationConfigResponseModel.prototype['password'] = undefined;

/**
 * @member {String} priority
 */
JiraIntegrationConfigResponseModel.prototype['priority'] = undefined;

/**
 * @member {String} project
 */
JiraIntegrationConfigResponseModel.prototype['project'] = undefined;

/**
 * @member {String} url
 */
JiraIntegrationConfigResponseModel.prototype['url'] = undefined;

/**
 * @member {String} username
 */
JiraIntegrationConfigResponseModel.prototype['username'] = undefined;






export default JiraIntegrationConfigResponseModel;

