/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProjectResponseModel from './ProjectResponseModel';

/**
 * The ListProjectsResponseModel model module.
 * @module model/ListProjectsResponseModel
 * @version 0.1.0
 */
class ListProjectsResponseModel {
    /**
     * Constructs a new <code>ListProjectsResponseModel</code>.
     * @alias module:model/ListProjectsResponseModel
     * @param items {Array.<module:model/ProjectResponseModel>} 
     * @param pgNum {Number} 
     * @param pgSize {Number} 
     */
    constructor(items, pgNum, pgSize) { 
        
        ListProjectsResponseModel.initialize(this, items, pgNum, pgSize);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, items, pgNum, pgSize) { 
        obj['items'] = items;
        obj['pg_num'] = pgNum;
        obj['pg_size'] = pgSize;
    }

    /**
     * Constructs a <code>ListProjectsResponseModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListProjectsResponseModel} obj Optional instance to populate.
     * @return {module:model/ListProjectsResponseModel} The populated <code>ListProjectsResponseModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListProjectsResponseModel();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [ProjectResponseModel]);
            }
            if (data.hasOwnProperty('pg_num')) {
                obj['pg_num'] = ApiClient.convertToType(data['pg_num'], 'Number');
            }
            if (data.hasOwnProperty('pg_size')) {
                obj['pg_size'] = ApiClient.convertToType(data['pg_size'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ProjectResponseModel>} items
 */
ListProjectsResponseModel.prototype['items'] = undefined;

/**
 * @member {Number} pg_num
 */
ListProjectsResponseModel.prototype['pg_num'] = undefined;

/**
 * @member {Number} pg_size
 */
ListProjectsResponseModel.prototype['pg_size'] = undefined;






export default ListProjectsResponseModel;

