/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IntegrationTypeResponseModel from './IntegrationTypeResponseModel';

/**
 * The ListIntegrationTypesResponseModel model module.
 * @module model/ListIntegrationTypesResponseModel
 * @version 0.1.0
 */
class ListIntegrationTypesResponseModel {
    /**
     * Constructs a new <code>ListIntegrationTypesResponseModel</code>.
     * @alias module:model/ListIntegrationTypesResponseModel
     * @param items {Array.<module:model/IntegrationTypeResponseModel>} 
     * @param pgNum {Number} 
     * @param pgSize {Number} 
     */
    constructor(items, pgNum, pgSize) { 
        
        ListIntegrationTypesResponseModel.initialize(this, items, pgNum, pgSize);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, items, pgNum, pgSize) { 
        obj['items'] = items;
        obj['pg_num'] = pgNum;
        obj['pg_size'] = pgSize;
    }

    /**
     * Constructs a <code>ListIntegrationTypesResponseModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListIntegrationTypesResponseModel} obj Optional instance to populate.
     * @return {module:model/ListIntegrationTypesResponseModel} The populated <code>ListIntegrationTypesResponseModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListIntegrationTypesResponseModel();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [IntegrationTypeResponseModel]);
            }
            if (data.hasOwnProperty('pg_num')) {
                obj['pg_num'] = ApiClient.convertToType(data['pg_num'], 'Number');
            }
            if (data.hasOwnProperty('pg_size')) {
                obj['pg_size'] = ApiClient.convertToType(data['pg_size'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/IntegrationTypeResponseModel>} items
 */
ListIntegrationTypesResponseModel.prototype['items'] = undefined;

/**
 * @member {Number} pg_num
 */
ListIntegrationTypesResponseModel.prototype['pg_num'] = undefined;

/**
 * @member {Number} pg_size
 */
ListIntegrationTypesResponseModel.prototype['pg_size'] = undefined;






export default ListIntegrationTypesResponseModel;

