/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LoginResponseModel model module.
 * @module model/LoginResponseModel
 * @version 0.1.0
 */
class LoginResponseModel {
    /**
     * Constructs a new <code>LoginResponseModel</code>.
     * @alias module:model/LoginResponseModel
     * @param displayName {String} 
     * @param isAdmin {Boolean} 
     * @param userId {String} 
     * @param userName {String} 
     */
    constructor(displayName, isAdmin, userId, userName) { 
        
        LoginResponseModel.initialize(this, displayName, isAdmin, userId, userName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, displayName, isAdmin, userId, userName) { 
        obj['display_name'] = displayName;
        obj['is_admin'] = isAdmin;
        obj['user_id'] = userId;
        obj['user_name'] = userName;
    }

    /**
     * Constructs a <code>LoginResponseModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoginResponseModel} obj Optional instance to populate.
     * @return {module:model/LoginResponseModel} The populated <code>LoginResponseModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoginResponseModel();

            if (data.hasOwnProperty('display_name')) {
                obj['display_name'] = ApiClient.convertToType(data['display_name'], 'String');
            }
            if (data.hasOwnProperty('is_admin')) {
                obj['is_admin'] = ApiClient.convertToType(data['is_admin'], 'Boolean');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
            if (data.hasOwnProperty('user_name')) {
                obj['user_name'] = ApiClient.convertToType(data['user_name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} display_name
 */
LoginResponseModel.prototype['display_name'] = undefined;

/**
 * @member {Boolean} is_admin
 */
LoginResponseModel.prototype['is_admin'] = undefined;

/**
 * @member {String} user_id
 */
LoginResponseModel.prototype['user_id'] = undefined;

/**
 * @member {String} user_name
 */
LoginResponseModel.prototype['user_name'] = undefined;






export default LoginResponseModel;

