/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ORMEngineID.
* @enum {}
* @readonly
*/
export default class ORMEngineID {
    
        /**
         * value: "afl"
         * @const
         */
        "afl" = "afl";

    
        /**
         * value: "afl.rs"
         * @const
         */
        "afl.rs" = "afl.rs";

    
        /**
         * value: "sharpfuzz-afl"
         * @const
         */
        "sharpfuzz-afl" = "sharpfuzz-afl";

    
        /**
         * value: "libfuzzer"
         * @const
         */
        "libfuzzer" = "libfuzzer";

    
        /**
         * value: "jazzer"
         * @const
         */
        "jazzer" = "jazzer";

    
        /**
         * value: "atheris"
         * @const
         */
        "atheris" = "atheris";

    
        /**
         * value: "cargo-fuzz"
         * @const
         */
        "cargo-fuzz" = "cargo-fuzz";

    
        /**
         * value: "go-fuzz-libfuzzer"
         * @const
         */
        "go-fuzz-libfuzzer" = "go-fuzz-libfuzzer";

    
        /**
         * value: "sharpfuzz-libfuzzer"
         * @const
         */
        "sharpfuzz-libfuzzer" = "sharpfuzz-libfuzzer";

    

    /**
    * Returns a <code>ORMEngineID</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ORMEngineID} The enum <code>ORMEngineID</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

