/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ORMLangID.
* @enum {}
* @readonly
*/
export default class ORMLangID {
    
        /**
         * value: "go"
         * @const
         */
        "go" = "go";

    
        /**
         * value: "cpp"
         * @const
         */
        "cpp" = "cpp";

    
        /**
         * value: "rust"
         * @const
         */
        "rust" = "rust";

    
        /**
         * value: "java"
         * @const
         */
        "java" = "java";

    
        /**
         * value: "swift"
         * @const
         */
        "swift" = "swift";

    
        /**
         * value: "python"
         * @const
         */
        "python" = "python";

    

    /**
    * Returns a <code>ORMLangID</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ORMLangID} The enum <code>ORMLangID</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

