/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ORMPoolResources model module.
 * @module model/ORMPoolResources
 * @version 0.1.0
 */
class ORMPoolResources {
    /**
     * Constructs a new <code>ORMPoolResources</code>.
     * @alias module:model/ORMPoolResources
     * @param cpu {Number} 
     * @param nodes {Number} 
     * @param ram {Number} 
     */
    constructor(cpu, nodes, ram) { 
        
        ORMPoolResources.initialize(this, cpu, nodes, ram);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cpu, nodes, ram) { 
        obj['cpu'] = cpu;
        obj['nodes'] = nodes;
        obj['ram'] = ram;
    }

    /**
     * Constructs a <code>ORMPoolResources</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ORMPoolResources} obj Optional instance to populate.
     * @return {module:model/ORMPoolResources} The populated <code>ORMPoolResources</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ORMPoolResources();

            if (data.hasOwnProperty('cpu')) {
                obj['cpu'] = ApiClient.convertToType(data['cpu'], 'Number');
            }
            if (data.hasOwnProperty('nodes')) {
                obj['nodes'] = ApiClient.convertToType(data['nodes'], 'Number');
            }
            if (data.hasOwnProperty('ram')) {
                obj['ram'] = ApiClient.convertToType(data['ram'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} cpu
 */
ORMPoolResources.prototype['cpu'] = undefined;

/**
 * @member {Number} nodes
 */
ORMPoolResources.prototype['nodes'] = undefined;

/**
 * @member {Number} ram
 */
ORMPoolResources.prototype['ram'] = undefined;






export default ORMPoolResources;

