/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PoolHealth.
* @enum {}
* @readonly
*/
export default class PoolHealth {
    
        /**
         * value: "Ok"
         * @const
         */
        "Ok" = "Ok";

    
        /**
         * value: "Warning"
         * @const
         */
        "Warning" = "Warning";

    
        /**
         * value: "Error"
         * @const
         */
        "Error" = "Error";

    

    /**
    * Returns a <code>PoolHealth</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PoolHealth} The enum <code>PoolHealth</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

