/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PoolHealth from './PoolHealth';
import PoolOperation from './PoolOperation';
import PoolResources from './PoolResources';

/**
 * The PoolResponseModel model module.
 * @module model/PoolResponseModel
 * @version 0.1.0
 */
class PoolResponseModel {
    /**
     * Constructs a new <code>PoolResponseModel</code>.
     * @alias module:model/PoolResponseModel
     * @param createdAt {String} 
     * @param description {String} 
     * @param health {module:model/PoolHealth} 
     * @param id {String} 
     * @param name {String} 
     * @param nodeGroup {Object} 
     * @param resources {module:model/PoolResources} 
     */
    constructor(createdAt, description, health, id, name, nodeGroup, resources) { 
        
        PoolResponseModel.initialize(this, createdAt, description, health, id, name, nodeGroup, resources);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, createdAt, description, health, id, name, nodeGroup, resources) { 
        obj['created_at'] = createdAt;
        obj['description'] = description;
        obj['health'] = health;
        obj['id'] = id;
        obj['name'] = name;
        obj['node_group'] = nodeGroup;
        obj['resources'] = resources;
    }

    /**
     * Constructs a <code>PoolResponseModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PoolResponseModel} obj Optional instance to populate.
     * @return {module:model/PoolResponseModel} The populated <code>PoolResponseModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PoolResponseModel();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('exp_date')) {
                obj['exp_date'] = ApiClient.convertToType(data['exp_date'], 'String');
            }
            if (data.hasOwnProperty('health')) {
                obj['health'] = PoolHealth.constructFromObject(data['health']);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('node_group')) {
                obj['node_group'] = ApiClient.convertToType(data['node_group'], Object);
            }
            if (data.hasOwnProperty('operation')) {
                obj['operation'] = PoolOperation.constructFromObject(data['operation']);
            }
            if (data.hasOwnProperty('resources')) {
                obj['resources'] = PoolResources.constructFromObject(data['resources']);
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} created_at
 */
PoolResponseModel.prototype['created_at'] = undefined;

/**
 * @member {String} description
 */
PoolResponseModel.prototype['description'] = undefined;

/**
 * @member {String} exp_date
 */
PoolResponseModel.prototype['exp_date'] = undefined;

/**
 * @member {module:model/PoolHealth} health
 */
PoolResponseModel.prototype['health'] = undefined;

/**
 * @member {String} id
 */
PoolResponseModel.prototype['id'] = undefined;

/**
 * @member {String} name
 */
PoolResponseModel.prototype['name'] = undefined;

/**
 * @member {Object} node_group
 */
PoolResponseModel.prototype['node_group'] = undefined;

/**
 * @member {module:model/PoolOperation} operation
 */
PoolResponseModel.prototype['operation'] = undefined;

/**
 * @member {module:model/PoolResources} resources
 */
PoolResponseModel.prototype['resources'] = undefined;

/**
 * @member {String} user_id
 */
PoolResponseModel.prototype['user_id'] = undefined;






export default PoolResponseModel;

