/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PoolNode model module.
 * @module model/PoolNode
 * @version 0.1.0
 */
class PoolNode {
    /**
     * Constructs a new <code>PoolNode</code>.
     * @alias module:model/PoolNode
     * @param cpu {Number} 
     * @param name {String} 
     * @param ram {Number} 
     */
    constructor(cpu, name, ram) { 
        
        PoolNode.initialize(this, cpu, name, ram);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cpu, name, ram) { 
        obj['cpu'] = cpu;
        obj['name'] = name;
        obj['ram'] = ram;
    }

    /**
     * Constructs a <code>PoolNode</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PoolNode} obj Optional instance to populate.
     * @return {module:model/PoolNode} The populated <code>PoolNode</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PoolNode();

            if (data.hasOwnProperty('cpu')) {
                obj['cpu'] = ApiClient.convertToType(data['cpu'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('ram')) {
                obj['ram'] = ApiClient.convertToType(data['ram'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} cpu
 */
PoolNode.prototype['cpu'] = undefined;

/**
 * @member {String} name
 */
PoolNode.prototype['name'] = undefined;

/**
 * @member {Number} ram
 */
PoolNode.prototype['ram'] = undefined;






export default PoolNode;

