/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProjectResponseModel model module.
 * @module model/ProjectResponseModel
 * @version 0.1.0
 */
class ProjectResponseModel {
    /**
     * Constructs a new <code>ProjectResponseModel</code>.
     * @alias module:model/ProjectResponseModel
     * @param description {String} 
     * @param id {String} 
     * @param name {String} 
     */
    constructor(description, id, name) { 
        
        ProjectResponseModel.initialize(this, description, id, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, description, id, name) { 
        obj['description'] = description;
        obj['id'] = id;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>ProjectResponseModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProjectResponseModel} obj Optional instance to populate.
     * @return {module:model/ProjectResponseModel} The populated <code>ProjectResponseModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProjectResponseModel();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('erasure_date')) {
                obj['erasure_date'] = ApiClient.convertToType(data['erasure_date'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('pool_id')) {
                obj['pool_id'] = ApiClient.convertToType(data['pool_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} description
 */
ProjectResponseModel.prototype['description'] = undefined;

/**
 * @member {String} erasure_date
 */
ProjectResponseModel.prototype['erasure_date'] = undefined;

/**
 * @member {String} id
 */
ProjectResponseModel.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ProjectResponseModel.prototype['name'] = undefined;

/**
 * @member {String} pool_id
 */
ProjectResponseModel.prototype['pool_id'] = undefined;






export default ProjectResponseModel;

