/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PutEnabledIntegrationRequestModel model module.
 * @module model/PutEnabledIntegrationRequestModel
 * @version 0.1.0
 */
class PutEnabledIntegrationRequestModel {
    /**
     * Constructs a new <code>PutEnabledIntegrationRequestModel</code>.
     * @alias module:model/PutEnabledIntegrationRequestModel
     * @param enabled {Boolean} 
     */
    constructor(enabled) { 
        
        PutEnabledIntegrationRequestModel.initialize(this, enabled);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, enabled) { 
        obj['enabled'] = enabled;
    }

    /**
     * Constructs a <code>PutEnabledIntegrationRequestModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PutEnabledIntegrationRequestModel} obj Optional instance to populate.
     * @return {module:model/PutEnabledIntegrationRequestModel} The populated <code>PutEnabledIntegrationRequestModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PutEnabledIntegrationRequestModel();

            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} enabled
 */
PutEnabledIntegrationRequestModel.prototype['enabled'] = undefined;






export default PutEnabledIntegrationRequestModel;

