/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetCrashResponseModel from './GetCrashResponseModel';

/**
 * The ResponseGetCrashOk model module.
 * @module model/ResponseGetCrashOk
 * @version 0.1.0
 */
class ResponseGetCrashOk {
    /**
     * Constructs a new <code>ResponseGetCrashOk</code>.
     * @alias module:model/ResponseGetCrashOk
     * @param operation {String} 
     * @param result {module:model/GetCrashResponseModel} 
     */
    constructor(operation, result) { 
        
        ResponseGetCrashOk.initialize(this, operation, result);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, operation, result) { 
        obj['operation'] = operation;
        obj['result'] = result;
    }

    /**
     * Constructs a <code>ResponseGetCrashOk</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResponseGetCrashOk} obj Optional instance to populate.
     * @return {module:model/ResponseGetCrashOk} The populated <code>ResponseGetCrashOk</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResponseGetCrashOk();

            if (data.hasOwnProperty('operation')) {
                obj['operation'] = ApiClient.convertToType(data['operation'], 'String');
            }
            if (data.hasOwnProperty('result')) {
                obj['result'] = GetCrashResponseModel.constructFromObject(data['result']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} operation
 */
ResponseGetCrashOk.prototype['operation'] = undefined;

/**
 * @member {module:model/GetCrashResponseModel} result
 */
ResponseGetCrashOk.prototype['result'] = undefined;

/**
 * @member {String} status
 * @default 'OK'
 */
ResponseGetCrashOk.prototype['status'] = 'OK';






export default ResponseGetCrashOk;

