/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PoolResponseModel from './PoolResponseModel';

/**
 * The ResponseCreatePoolOk model module.
 * @module model/ResponseCreatePoolOk
 * @version 0.1.0
 */
class ResponseCreatePoolOk {
    /**
     * Constructs a new <code>ResponseCreatePoolOk</code>.
     * @alias module:model/ResponseCreatePoolOk
     * @param result {module:model/PoolResponseModel} 
     */
    constructor(result) { 
        
        ResponseCreatePoolOk.initialize(this, result);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, result) { 
        obj['result'] = result;
    }

    /**
     * Constructs a <code>ResponseCreatePoolOk</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResponseCreatePoolOk} obj Optional instance to populate.
     * @return {module:model/ResponseCreatePoolOk} The populated <code>ResponseCreatePoolOk</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResponseCreatePoolOk();

            if (data.hasOwnProperty('result')) {
                obj['result'] = PoolResponseModel.constructFromObject(data['result']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/PoolResponseModel} result
 */
ResponseCreatePoolOk.prototype['result'] = undefined;






export default ResponseCreatePoolOk;

