/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RevisionResponseModel model module.
 * @module model/RevisionResponseModel
 * @version 0.1.0
 */
class RevisionResponseModel {
    /**
     * Constructs a new <code>RevisionResponseModel</code>.
     * @alias module:model/RevisionResponseModel
     * @param binaries {Object} 
     * @param config {Object} 
     * @param cpuUsage {Number} 
     * @param created {String} 
     * @param description {String} 
     * @param health {String} 
     * @param id {String} 
     * @param imageId {String} 
     * @param name {String} 
     * @param ramUsage {Number} 
     * @param seeds {Object} 
     * @param status {String} 
     * @param tmpfsSize {Number} 
     */
    constructor(binaries, config, cpuUsage, created, description, health, id, imageId, name, ramUsage, seeds, status, tmpfsSize) { 
        
        RevisionResponseModel.initialize(this, binaries, config, cpuUsage, created, description, health, id, imageId, name, ramUsage, seeds, status, tmpfsSize);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, binaries, config, cpuUsage, created, description, health, id, imageId, name, ramUsage, seeds, status, tmpfsSize) { 
        obj['binaries'] = binaries;
        obj['config'] = config;
        obj['cpu_usage'] = cpuUsage;
        obj['created'] = created;
        obj['description'] = description;
        obj['health'] = health;
        obj['id'] = id;
        obj['image_id'] = imageId;
        obj['name'] = name;
        obj['ram_usage'] = ramUsage;
        obj['seeds'] = seeds;
        obj['status'] = status;
        obj['tmpfs_size'] = tmpfsSize;
    }

    /**
     * Constructs a <code>RevisionResponseModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RevisionResponseModel} obj Optional instance to populate.
     * @return {module:model/RevisionResponseModel} The populated <code>RevisionResponseModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RevisionResponseModel();

            if (data.hasOwnProperty('binaries')) {
                obj['binaries'] = ApiClient.convertToType(data['binaries'], Object);
            }
            if (data.hasOwnProperty('config')) {
                obj['config'] = ApiClient.convertToType(data['config'], Object);
            }
            if (data.hasOwnProperty('cpu_usage')) {
                obj['cpu_usage'] = ApiClient.convertToType(data['cpu_usage'], 'Number');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('erasure_date')) {
                obj['erasure_date'] = ApiClient.convertToType(data['erasure_date'], 'String');
            }
            if (data.hasOwnProperty('feedback')) {
                obj['feedback'] = ApiClient.convertToType(data['feedback'], Object);
            }
            if (data.hasOwnProperty('health')) {
                obj['health'] = ApiClient.convertToType(data['health'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('image_id')) {
                obj['image_id'] = ApiClient.convertToType(data['image_id'], 'String');
            }
            if (data.hasOwnProperty('last_start_date')) {
                obj['last_start_date'] = ApiClient.convertToType(data['last_start_date'], 'String');
            }
            if (data.hasOwnProperty('last_stop_date')) {
                obj['last_stop_date'] = ApiClient.convertToType(data['last_stop_date'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('ram_usage')) {
                obj['ram_usage'] = ApiClient.convertToType(data['ram_usage'], 'Number');
            }
            if (data.hasOwnProperty('seeds')) {
                obj['seeds'] = ApiClient.convertToType(data['seeds'], Object);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('tmpfs_size')) {
                obj['tmpfs_size'] = ApiClient.convertToType(data['tmpfs_size'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Object} binaries
 */
RevisionResponseModel.prototype['binaries'] = undefined;

/**
 * @member {Object} config
 */
RevisionResponseModel.prototype['config'] = undefined;

/**
 * @member {Number} cpu_usage
 */
RevisionResponseModel.prototype['cpu_usage'] = undefined;

/**
 * @member {String} created
 */
RevisionResponseModel.prototype['created'] = undefined;

/**
 * @member {String} description
 */
RevisionResponseModel.prototype['description'] = undefined;

/**
 * @member {String} erasure_date
 */
RevisionResponseModel.prototype['erasure_date'] = undefined;

/**
 * @member {Object} feedback
 */
RevisionResponseModel.prototype['feedback'] = undefined;

/**
 * @member {String} health
 */
RevisionResponseModel.prototype['health'] = undefined;

/**
 * @member {String} id
 */
RevisionResponseModel.prototype['id'] = undefined;

/**
 * @member {String} image_id
 */
RevisionResponseModel.prototype['image_id'] = undefined;

/**
 * @member {String} last_start_date
 */
RevisionResponseModel.prototype['last_start_date'] = undefined;

/**
 * @member {String} last_stop_date
 */
RevisionResponseModel.prototype['last_stop_date'] = undefined;

/**
 * @member {String} name
 */
RevisionResponseModel.prototype['name'] = undefined;

/**
 * @member {Number} ram_usage
 */
RevisionResponseModel.prototype['ram_usage'] = undefined;

/**
 * @member {Object} seeds
 */
RevisionResponseModel.prototype['seeds'] = undefined;

/**
 * @member {String} status
 */
RevisionResponseModel.prototype['status'] = undefined;

/**
 * @member {Number} tmpfs_size
 */
RevisionResponseModel.prototype['tmpfs_size'] = undefined;






export default RevisionResponseModel;

