/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateResponseModel model module.
 * @module model/UpdateResponseModel
 * @version 0.1.0
 */
class UpdateResponseModel {
    /**
     * Constructs a new <code>UpdateResponseModel</code>.
     * @alias module:model/UpdateResponseModel
     * @param _new {Object} 
     * @param old {Object} 
     */
    constructor(_new, old) { 
        
        UpdateResponseModel.initialize(this, _new, old);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, _new, old) { 
        obj['new'] = _new;
        obj['old'] = old;
    }

    /**
     * Constructs a <code>UpdateResponseModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateResponseModel} obj Optional instance to populate.
     * @return {module:model/UpdateResponseModel} The populated <code>UpdateResponseModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateResponseModel();

            if (data.hasOwnProperty('new')) {
                obj['new'] = ApiClient.convertToType(data['new'], Object);
            }
            if (data.hasOwnProperty('old')) {
                obj['old'] = ApiClient.convertToType(data['old'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {Object} new
 */
UpdateResponseModel.prototype['new'] = undefined;

/**
 * @member {Object} old
 */
UpdateResponseModel.prototype['old'] = undefined;






export default UpdateResponseModel;

