/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateIntegrationRequestModel model module.
 * @module model/UpdateIntegrationRequestModel
 * @version 0.1.0
 */
class UpdateIntegrationRequestModel {
    /**
     * Constructs a new <code>UpdateIntegrationRequestModel</code>.
     * @alias module:model/UpdateIntegrationRequestModel
     */
    constructor() { 
        
        UpdateIntegrationRequestModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateIntegrationRequestModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateIntegrationRequestModel} obj Optional instance to populate.
     * @return {module:model/UpdateIntegrationRequestModel} The populated <code>UpdateIntegrationRequestModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateIntegrationRequestModel();

            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} enabled
 */
UpdateIntegrationRequestModel.prototype['enabled'] = undefined;

/**
 * @member {String} name
 */
UpdateIntegrationRequestModel.prototype['name'] = undefined;






export default UpdateIntegrationRequestModel;

