/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateEngineRequestModel model module.
 * @module model/UpdateEngineRequestModel
 * @version 0.1.0
 */
class UpdateEngineRequestModel {
    /**
     * Constructs a new <code>UpdateEngineRequestModel</code>.
     * @alias module:model/UpdateEngineRequestModel
     */
    constructor() { 
        
        UpdateEngineRequestModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateEngineRequestModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateEngineRequestModel} obj Optional instance to populate.
     * @return {module:model/UpdateEngineRequestModel} The populated <code>UpdateEngineRequestModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateEngineRequestModel();

            if (data.hasOwnProperty('display_name')) {
                obj['display_name'] = ApiClient.convertToType(data['display_name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} display_name
 */
UpdateEngineRequestModel.prototype['display_name'] = undefined;






export default UpdateEngineRequestModel;

