/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateRevisionInfoRequestModel model module.
 * @module model/UpdateRevisionInfoRequestModel
 * @version 0.1.0
 */
class UpdateRevisionInfoRequestModel {
    /**
     * Constructs a new <code>UpdateRevisionInfoRequestModel</code>.
     * @alias module:model/UpdateRevisionInfoRequestModel
     */
    constructor() { 
        
        UpdateRevisionInfoRequestModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateRevisionInfoRequestModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateRevisionInfoRequestModel} obj Optional instance to populate.
     * @return {module:model/UpdateRevisionInfoRequestModel} The populated <code>UpdateRevisionInfoRequestModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateRevisionInfoRequestModel();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} description
 */
UpdateRevisionInfoRequestModel.prototype['description'] = undefined;

/**
 * @member {String} name
 */
UpdateRevisionInfoRequestModel.prototype['name'] = undefined;






export default UpdateRevisionInfoRequestModel;

