/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateLangRequestModel model module.
 * @module model/UpdateLangRequestModel
 * @version 0.1.0
 */
class UpdateLangRequestModel {
    /**
     * Constructs a new <code>UpdateLangRequestModel</code>.
     * @alias module:model/UpdateLangRequestModel
     */
    constructor() { 
        
        UpdateLangRequestModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateLangRequestModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateLangRequestModel} obj Optional instance to populate.
     * @return {module:model/UpdateLangRequestModel} The populated <code>UpdateLangRequestModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateLangRequestModel();

            if (data.hasOwnProperty('display_name')) {
                obj['display_name'] = ApiClient.convertToType(data['display_name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} display_name
 */
UpdateLangRequestModel.prototype['display_name'] = undefined;






export default UpdateLangRequestModel;

